// SEO Structured Data Component - Add to your pages for rich snippets

export const generateFAQSchema = () => {
  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    'mainEntity': [
      {
        '@type': 'Question',
        'name': 'How does Ramadan Bot generate Islamic reflections with AI?',
        'acceptedAnswer': {
          '@type': 'Answer',
          'text': 'Ramadan Bot uses advanced AI trained on authentic Islamic knowledge including Quranic verses and Hadiths to generate personalized daily spiritual reflections. Each reflection is unique, meaningful, and grounded in Islamic teachings.'
        }
      },
      {
        '@type': 'Question',
        'name': 'Can I get personalized flyers with my name featured for free?',
        'acceptedAnswer': {
          '@type': 'Answer',
          'text': 'Yes! Every flyer generated by Ramadan Bot features your name prominently in beautiful, high-resolution 1080x1080px designs. It\'s completely free with no premium version - unlimited flyer generation.'
        }
      },
      {
        '@type': 'Question',
        'name': 'How do I install Ramadan Bot as a native Android app?',
        'acceptedAnswer': {
          '@type': 'Answer',
          'text': 'Visit ramadanbot.app/app on your Android device, tap the menu, and select "Add to Home Screen". This installs Ramadan Bot as a PWA (Progressive Web App) that works like a native app with offline capabilities.'
        }
      },
      {
        '@type': 'Question',
        'name': 'Is my personal information kept private in Ramadan Bot?',
        'acceptedAnswer': {
          '@type': 'Answer',
          'text': 'Absolutely. Ramadan Bot only requires your name and a 4-digit PIN. No email, phone number, or sensitive data is collected. Your privacy is our top priority - we never share or track your personal information.'
        }
      },
      {
        '@type': 'Question',
        'name': 'What happens if I miss a day in my Ramadan spiritual streak?',
        'acceptedAnswer': {
          '@type': 'Answer',
          'text': 'Your streak will reset, but every day is a new opportunity. Use Ramadan Bot to generate your next reflection and start building accountability again with your community.'
        }
      },
      {
        '@type': 'Question',
        'name': 'Is Ramadan Bot completely free or does it have premium features?',
        'acceptedAnswer': {
          '@type': 'Answer',
          'text': 'Ramadan Bot is 100% free with no hidden costs or premium tiers. You get unlimited access to 3 daily AI-generated reflections, beautiful flyer creation, social sharing, and streak tracking - forever free.'
        }
      },
      {
        '@type': 'Question',
        'name': 'Can I share Ramadan Bot flyers to WhatsApp, Instagram, and TikTok?',
        'acceptedAnswer': {
          '@type': 'Answer',
          'text': 'Yes, with one tap! Ramadan Bot supports direct sharing to WhatsApp, Instagram, X (Twitter), TikTok, Facebook, Snapchat, and email. You can also download high-resolution PNGs.'
        }
      },
      {
        '@type': 'Question',
        'name': 'Who created Ramadan Bot - the personalized Islamic flyer generator?',
        'acceptedAnswer': {
          '@type': 'Answer',
          'text': 'Ramadan Bot was created by Abdallah Nangere, a developer passionate about building technology that deepens Islamic spirituality and community. Follow @Abdalla_Nangere on X (Twitter) for updates.'
        }
      }
    ]
  };
};

export const generateBreadcrumbSchema = (path: string) => {
  const breadcrumbs: Record<string, Array<{ '@type': string; 'position': number; 'name': string; 'item'?: string }>> = {
    '/': [
      { '@type': 'ListItem', 'position': 1, 'name': 'Home', 'item': 'https://www.ramadanbot.app' }
    ],
    '/app': [
      { '@type': 'ListItem', 'position': 1, 'name': 'Home', 'item': 'https://www.ramadanbot.app' },
      { '@type': 'ListItem', 'position': 2, 'name': 'App' }
    ],
    '/privacy': [
      { '@type': 'ListItem', 'position': 1, 'name': 'Home', 'item': 'https://www.ramadanbot.app' },
      { '@type': 'ListItem', 'position': 2, 'name': 'Privacy' }
    ],
    '/contact': [
      { '@type': 'ListItem', 'position': 1, 'name': 'Home', 'item': 'https://www.ramadanbot.app' },
      { '@type': 'ListItem', 'position': 2, 'name': 'Contact' }
    ]
  };

  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    'itemListElement': breadcrumbs[path] || breadcrumbs['/']
  };
};

export const generateImageSchema = (imagePath: string, description: string) => {
  return {
    '@context': 'https://schema.org',
    '@type': 'ImageObject',
    'url': `https://www.ramadanbot.app${imagePath}`,
    'name': description,
    'description': description,
    'image': `https://www.ramadanbot.app${imagePath}`
  };
};

export const generateVideoSchema = () => {
  return {
    '@context': 'https://schema.org',
    '@type': 'VideoObject',
    'name': 'Ramadan Bot - Create Islamic Reflections & Personalized Flyers',
    'description': 'See how Ramadan Bot helps you generate authentic Islamic reflections and share beautiful personalized flyers with your name featured',
    'thumbnailUrl': 'https://www.ramadanbot.app/logo.png',
    'uploadDate': new Date().toISOString().split('T')[0],
    'duration': 'PT2M',
    'contentUrl': 'https://www.ramadanbot.app/demo-video.mp4'
  };
};

export const generateArticleSchema = (title: string, description: string, datePublished: string, dateModified: string) => {
  return {
    '@context': 'https://schema.org',
    '@type': 'Article',
    'headline': title,
    'description': description,
    'image': 'https://www.ramadanbot.app/logo.png',
    'datePublished': datePublished,
    'dateModified': dateModified,
    'author': {
      '@type': 'Person',
      'name': 'Abdallah Nangere'
    },
    'publisher': {
      '@type': 'Organization',
      'name': 'Ramadan Bot',
      'logo': {
        '@type': 'ImageObject',
        'url': 'https://www.ramadanbot.app/logo.png'
      }
    }
  };
};

export const generateLocalBusinessSchema = () => {
  return {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    'name': 'Ramadan Bot',
    'url': 'https://www.ramadanbot.app',
    'image': 'https://www.ramadanbot.app/logo.png',
    'description': 'AI-powered Islamic reflection generator and personalized Ramadan flyer creator',
    'founder': {
      '@type': 'Person',
      'name': 'Abdallah Nangere'
    },
    'contactPoint': {
      '@type': 'ContactPoint',
      'url': 'https://www.ramadanbot.app/contact',
      'contactType': 'Customer Support'
    }
  };
};
